name: Deploy to RackStation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to RackStation
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.RACKSTATION_HOST }}
        username: mike
        key: ${{ secrets.RACKSTATION_SSH_KEY }}
        script: |
          cd /path/to/your/app
          ./deploy.sh
